import { OrderStats } from "../enums/order-stats/order-stats";

export const OrderStatsList = [
    {   key: OrderStats.OrderPlaced,
        prodCount: 45,
        classes: 'ordered',
        color: '#4EA3F8',
        label: 'my-orders.ordered',
        iconHeight: 40,
        iconPath: 'assets/media/modules/profile/icons/order-status/ordered.svg',
        activeIconPath: 'assets/media/modules/profile/icons/order-status/ordered-white.svg',
    },
    {   key: OrderStats.Shipping,
        prodCount: 45,
        classes: 'shipping',
        color: '#fca908',
        label: 'my-orders.shipping',
        iconHeight: 40,
        iconPath: 'assets/media/modules/profile/icons/order-status/shipping.svg',
        activeIconPath: 'assets/media/modules/profile/icons/order-status/shipping-white.svg',
    },
    {   key: OrderStats.Delivered,
        prodCount: 45,
        classes: 'delivered',
        color: '#02A207',
        label: 'my-orders.delivered',
        iconHeight: 40,
        iconPath: 'assets/media/modules/profile/icons/order-status/delivered.svg',
        activeIconPath: 'assets/media/modules/profile/icons/order-status/delivered-white.svg',
    },
    {   key: OrderStats.Returned,
        prodCount: 45,
        classes: 'returned',
        color: '#F4D014',
        label: 'my-orders.returned',
        iconHeight: 40,
        iconPath: 'assets/media/modules/profile/icons/order-status/returned.svg',
        activeIconPath: 'assets/media/modules/profile/icons/order-status/returned-white.svg',
    },
    {   key: OrderStats.Canceled,
        prodCount: 45,
        classes: 'cancelled',
        color: '#FA0029',
        label: 'my-orders.cancelled',
        iconHeight: 40,
        iconPath: 'assets/media/modules/profile/icons/order-status/canceled.svg',
        activeIconPath: 'assets/media/modules/profile/icons/order-status/canceled-white.svg',
    },
]